name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
      - develop
      - develop8.1

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_NAME: 'release-drafter-${{ github.ref }}.yml'
    steps:
      - name: Extract branch name
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo release-drafter-${GITHUB_REF#refs/heads/}.yml)"
          echo ${GITHUB_REF#refs/heads/}
          echo (steps.default_branch.outputs.branch )
        id: extract_branch
       
      - name: Print Release Drafter Config File Name 
        run: |
          write-host ${{ steps.extract_branch.outputs.branch }}
        shell: pwsh
        
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: ${{ steps.extract_branch.outputs.branch }} # located in .github/ in default branch
